[book]
authors = ["lzzsG"]
language = "en"
multilingual = false
src = "src"
title = "rCore Series Notebook"

[output.html]
default-theme = "black"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/lzzsG/rCore-series"
preferred-dark-theme = "black"
site-url = "/rCore-series/"

[output.html.playground]
editable = true
